conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import UserListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace = 'users')),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import UserListView, UserRegisterView, UserDetailView, UserDownloadView

app_name = 'users'

urlpatterns = [
    path('', UserListView, name='list'),
    path('register/', UserRegisterView, name='register'),
    path('<int:pk>/', UserDetailView, name='detail'),
    path('download/<int:pk>/', UserDownloadView, name='download'),
]

users/models.py
from django.db import models

class UserModel(models.Model):
    full_name = models.CharField(max_length=128)
    age = models.IntegerField()
    phone_number = models.CharField(max_length=13)

    email = models.EmailField()
    region = models.CharField(max_length=20)
    certificate = models.FileField(upload_to="media/certificates", null=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

users/forms.py
from django import forms

from users.models import UserModel


class UserModelForms(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ['full_name', 'age', 'phone_number', 'email', 'region', 'certificate']

users/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from users.forms import UserModelForms
from users.models import UserModel


def UserListView(request):
    users = UserModel.objects.all()
    q = request.GET.get('q')
    if q:
        users = users.filter(full_name__icontains = q)
    context = {
        'users': users,
    }

    return render(request, 'user-list.html', context=context)


def UserRegisterView(request):
    if request.method == 'POST':
        form = UserModelForms(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('users:list')
        else:
            return HttpResponse('We Could Not Add The User To Our Database!')

    else:
        return render(request, 'user-register.html')


def UserDetailView(request, pk):
    current_user = UserModel.objects.filter(id=pk).first()
    if current_user:
        context = {
            'user': current_user,
        }

        return render(request, 'user-detail.html', context=context)
    else:
        return HttpResponse('User Could Not Be Found!')


def UserDownloadView(request, pk):
    current_user = UserModel.objects.filter(id=pk).first()
    print(current_user.certificate)
    if current_user:
            file_path = current_user.certificate.path
            with open(file_path, 'rb') as f:
                response = HttpResponse(f.read(), content_type='application/pdf')
                return response
    else:
        return HttpResponse('User Could Not Be Found!')

templates/user-detail.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Details</title>
    <link rel="stylesheet" href="{% static 'css/user-detail.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>
<div class="container">
    <h1>User Details</h1>
    <div class="user-detail">
        <strong>Full Name:</strong> {{user.full_name}}
    </div>
    <div class="user-detail">
        <strong>Age:</strong> {{user.age}}
    </div>
    <div class="user-detail">
        <strong>Phone Number:</strong> {{user.phone_number}}
    </div>
    <div class="user-detail">
        <strong>Email:</strong> {{user.email}}
    </div>
    <div class="user-detail">
        <strong>Region:</strong> {{user.region}}
    </div>
    <div class="user-detail">
        <strong>Certificate:</strong><a style="color:black" href="{%url 'users:download' pk=user.id %}"><i
            class="fa-solid fa-file"></i> Download</a>
    </div>


    <a style="color:black" href="{% url 'users:list' %}">
        <button type="button" class="btn btn-secondary">Back</button>
    </a>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</div>
</body>
</html>

templates/user-list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse container mt-3" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" style="color:black" href="{% url 'users:list' %}"> Home  <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                   value="{{ request.GET.q }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            <a style="color:black" href="{% url 'users:register' %}">
                <button type="button" class="btn btn-secondary">Register</button>
            </a>
        </form>
    </div>
</nav>

<div class="container mt-3">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th width="10%" scope="col">#</th>
            <th width="60%" scope="col">Full Name</th>
            <th width="10%" scope="col">Age</th>
            <th width="20%" scope="col">Phone Number</th>
        </tr>
        </thead>

        <tbody>
        {% for user in users %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a style="color:black" href="{%url 'users:detail' pk=user.id%}">
                {{user.full_name}}</a></td>
            <td><a style="color:black" href="{%url 'users:detail' pk=user.id%}">{{user.age}}</a></td>
            <td><a style="color:black" href="{%url 'users:detail' pk=user.id%}">{{user.phone_number}}</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/user-register.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Page</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container">
    <h2>Register</h2>
    <form action="{% url 'users:register' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="full_name">Full Name</label>
        <input type="text" id="full_name" name="full_name" required>

        <label for="age">Age</label>
        <input type="number" id="age" name="age" required>

        <label for="phone_number">Phone Number</label>
        <input type="text" id="phone_number" name="phone_number" required>

        <label for="email">Email</label>
        <input type="email" id="email" name="email" required>

        <label for="region">Region</label>
        <select id="region" name="region" required>
            <option value="">Select Region</option>
            <option value="Andijon">Andijon</option>
            <option value="Buxoro">Buxoro</option>
            <option value="Fargʻona">Fargʻona</option>
            <option value="Jizzax">Jizzax</option>
            <option value="Xorazm">Xorazm</option>
            <option value="Namangan">Namangan</option>
            <option value="Navoiy">Navoiy</option>
            <option value="Qashqadaryo">Qashqadaryo</option>
            <option value="Samarqand">Samarqand</option>
            <option value="Sirdaryo">Sirdaryo</option>
            <option value="Surxondaryo">Surxondaryo</option>
            <option value="Toshkent Shahri">Toshkent Shahri</option>
            <option value="Toshkent viloyati">Toshkent viloyati</option>
        </select>

        <label for="certificate">Certificate</label>
        <input type="file" id="certificate" name="certificate" required>

        <input type="submit" value="submit">
    </form>
</div>
</body>
</html>